name: "ServiceOwners"
description: "Repo-native service ownership mapping + PR impact summary (SERVICEOWNERS)"
author: "binbandit"
branding:
  icon: "map"
  color: "blue"

inputs:
  token:
    description: "GitHub token for commenting on PRs (defaults to github.token)"
    required: false
    default: ""
  serviceowners_file:
    description: "Path to SERVICEOWNERS file"
    required: false
    default: "SERVICEOWNERS"
  services_file:
    description: "Path to services.yaml file (optional)"
    required: false
    default: "services.yaml"
  diff:
    description: "Override diff range (otherwise derived from GitHub event)"
    required: false
    default: ""
  comment:
    description: "true/false - comment on PR"
    required: false
    default: "true"
  fail_on_unmapped:
    description: "true/false - fail if unmapped files exist"
    required: false
    default: "true"
  strict_lint:
    description: "true/false - treat lint warnings as errors"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install ServiceOwners
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${{ github.action_path }}"

    - name: Run ServiceOwners
      shell: bash
      env:
        # If inputs.token is empty, this falls back to the workflow token automatically.
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        EXTRA_DIFF=""
        if [ -n "${{ inputs.diff }}" ]; then
          EXTRA_DIFF="--diff ${{ inputs.diff }}"
        fi

        sowners action \
          --serviceowners-file "${{ inputs.serviceowners_file }}" \
          --services-file "${{ inputs.services_file }}" \
          $EXTRA_DIFF \
          --comment "${{ inputs.comment }}" \
          --fail-on-unmapped "${{ inputs.fail_on_unmapped }}" \
          --strict-lint "${{ inputs.strict_lint }}"
