name: "ServiceOwners"
description: "Repo-native service ownership mapping + PR impact summary"
author: "binbandit"
branding:
  icon: "map"
  color: "orange"

inputs:
  token:
    description: "GitHub token"
    required: false
    default: ""
  serviceowners_file:
    description: "Path to SERVICEOWNERS file"
    required: false
    default: "SERVICEOWNERS"
  services_file:
    description: "Path to services.yaml file"
    required: false
    default: "services.yaml"
  diff:
    description: "Override diff range"
    required: false
    default: ""
  comment:
    description: "true/false - comment on PR"
    required: false
    default: "true"
  fail_on_unmapped:
    description: "true/false - fail if unmapped files exist"
    required: false
    default: "true"
  strict_lint:
    description: "true/false - strict lint"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cache Rust Build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/sowners
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-sowners-v2-${{ hashFiles('**/Cargo.lock') }}

    - name: Install ServiceOwners
      shell: bash
      run: |
        if ! command -v sowners &> /dev/null; then
          echo "Building ServiceOwners from source..."
          cargo install --path "${{ github.action_path }}"
        fi

    - name: Run ServiceOwners
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        DIFF_ARG=""
        if [ -n "${{ inputs.diff }}" ]; then
          DIFF_ARG="--diff ${{ inputs.diff }}"
        fi

        sowners action \
          --serviceowners-file "${{ inputs.serviceowners_file }}" \
          $DIFF_ARG \
          --comment "${{ inputs.comment }}" \
          --fail-on-unmapped "${{ inputs.fail_on_unmapped }}" \
          --strict-lint "${{ inputs.strict_lint }}"
